name: Build Win32 EotC Godot
on:
  workflow_call:
    inputs:
      cache-name:
        description: Key to use for caching.
        required: true
        type: string
      platform:
        description: Target platform.
        default: "linuxbsd"
        required: false
        type: string
      target:
        description: Build target (editor, template_release, template_debug).
        default: "editor"
        type: string
      sconsflags:
        default: ""
        type: string
      bin:
        description: The path to the built Godot executable.
        type: string
      tests:
        description: Unit tests.
        default: false
        type: boolean
      build-mono:
        description: Whether to build the mono glue or not.
        default: false
        type: boolean
      glue-dump:
        description: Dump the generated glue sources for use in other workflows.
        default: false
        type: boolean
      artifact:
        description: Whether to save an artifact or not.
        default: true
        type: boolean

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra #module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TSAN_OPTIONS: suppressions=misc/error_suppressions/tsan.txt

jobs:
  eotc-godot-build:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: ${{ inputs.cache-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ inputs.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Setup MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ inputs.sconsflags }}
          platform: windows
          target: ${{ inputs.target }}
          tests: ${{ inputs.tests }}

      - name: Generate C# glue
        if: ${{ inputs.build-mono }}
        run: |
          ${{ inputs.bin }} --headless --generate-mono-glue ./modules/mono/glue

      - name: Build .NET solutions
        if: ${{ inputs.build-mono }}
        run: |
          ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=${{ inputs.platform }}

      - name: Prepare artifact
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ inputs.cache-name }}

      # Execute unit tests for the editor
      - name: Unit tests
        if: ${{ inputs.tests }}
        run: |
          ${{ inputs.bin }} --version
          ${{ inputs.bin }} --help
          ${{ inputs.bin }} --test --force-colors

  # build-win32-templates:
  #   name: Build Win32 Export Templates
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - name: Windows Editor w/ Mono (target=editor)
  #           cache-name: eotc-windows-editor-mono
  #           platform: "windows"
  #           target: editor
  #           sconsflags: debug_symbols=no vsproj=yes vsproj_gen_only=no windows_subsystem=console #production=yes
  #           bin: "./bin/godot.windows.editor.x86_64.exe"
  #           build-mono: true
  #           tests: false
  #           artifact: true

  #         - name: Windows Template w/ Mono (target=template_debug)
  #           cache-name: eotc-windows-template-debug-mono
  #           platform: "windows"
  #           target: template_debug
  #           sconsflags: debug_symbols=no arch=x86_64 module_mono_enabled=yes #production=yes
  #           build-mono: false
  #           tests: false
  #           artifact: true

  #         - name: Windows Template w/ Mono (target=template_release)
  #           cache-name: eotc-windows-template-release-mono
  #           platform: "windows"
  #           target: template_release
  #           sconsflags: debug_symbols=no arch=x86_64 module_mono_enabled=yes #production=yes
  #           build-mono: false
  #           tests: false
  #           artifact: true

  #   uses: ./.github/workflows/eotc_win32_godot_build.yml
  #   with:
  #     cache-name: ${{ matrix.cache-name }}
  #     platform: ${{ matrix.platform }}
  #     target: ${{ matrix.target }}
  #     sconsflags: ${{ matrix.sconsflags }}
  #     bin: ${{ matrix.bin }}
  #     build-mono: ${{ matrix.build-mono }}
  #     tests: ${{ matrix.tests }}
  #     artifact: ${{ matrix.artifact }}
